### ISSUE TITLE
Possible Bug in "Bearbeitungen pro Tag"

### ISSUE THREAD

**Issue by kulla** [serlo/stats.serlo.org#109]
Fehlerbeschreibung (Zitat): Eine Frage zum Board "Bearbeitungen pro Tag."
Hier habe ich festgestellt, dass #Selbstreview=#Ohne Review für fast alle Tage gilt. Kann es sein, dass wenn jmd mit Reviewrechten einen Inhalt auscheckt automatisch für beide Kategorien ein Event getriggert wird

**Comment by yolo-bird** [comment]
Moved to backlog
