### ISSUE TITLE
Identify subjects with language-tenant

### ISSUE THREAD

**Issue by jakobwes** [serlo/stats.serlo.org#141]
At the moment it very difficult to track the KPIs for the LCU and for different subjects because of the number of subjects existing. It would be very helpful to have displayed the correct subject-names and some kind of identification with the language-tenant

**Comment by kulla** [comment]
The character encoding issue is due to https://github.com/serlo/serlo.org/issues/166 an thus tracked there. For identifying the language version having the name of the subject to be `<language version>: <subject name>` is enough?

**Comment by jakobwes** [comment]
That would be perfect and would make the identification a lot easier!

**Comment by Lodifice** [comment]
I'd like to add that the subjects are already sorted manually in some sense so that most desired ones are at the top. If you want some subject to appear closer to the top, just ask.

**Comment by jakobwes** [comment]
That is already a cool feature! The problem is more that for example every language-version has a community-subject (with all new topics,... inside), so we have 4/5 community-subjects on stats.serlo.org and several subjects named test,... There I don't really know what subject is related to what language-version

**Comment by yolo-bird** [comment]
Moved to our backlog document: https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#heading=h.naztbrq10z8g
