### ISSUE TITLE
Dashboard: Pro Fach Liste der aktuellen aktiven Autor*innen + welcher ist davon aktiver Reviewer?

### ISSUE THREAD

**Issue by kulla** [serlo/stats.serlo.org#92]
* Aufgabe: Pro Fach soll es eine Tabelle geben mit der Liste der aktuell aktiven Autor*innen (10 Bearbeitungen in den letzten 90 Tagen), es soll auch angezeigt werden, wer davon aktuell aktiver Reviewer ist (10 Reviews in den letzten 90 Tagen)
* Hintergrund: Diese Liste soll genutzt werden, um neue potentielle Reviewer zu finden und für das Reviewing anzuwerben

**Comment by Lodifice** [comment]
Offen: rekursive Berechnung der Entity-Fachbeziehungen (vgl. https://github.com/serlo/serlo.org/blob/master/packages/public/server/src/module/Entity/src/Entity/Entity/Entity.php#L263)
